import { useContext } from 'react'
import { LanguageContext } from '../contexts/LanguageContextDefinition'

const translations = {
  // English translations
  en: {
    postNotFound: 'Post not found.',
    commentNotFound: 'Comment not found.',
    liked: 'Liked',
    unliked: 'Unliked',
    postCreated: 'Post created successfully.',
    commentCreated: 'Comment posted successfully.',
    notFound: 'Not found.',
    clickTracked: 'Click tracked.',
    bookmarked: 'Bookmarked.',
    unbookmarked: 'Bookmark removed.',
    types: 'Types',
    
    // Add your Header translations
    home: 'Home',
    about: 'About',
    forum: 'Forum',
    opportunities: 'Opportunities',
    resources: 'Resources',
    view_profile: 'View Profile',
    dashboard: 'Dashboard',
    settings: 'Settings',
    help: 'Help',
    report_safety_concern: 'Report Safety Concern',
    log_out: 'Log Out',
    login: 'Login',
    register: 'Register',
    sharezone: 'ShareZone',
    
    // About page translations
    hero_title: 'Every Girl Deserves Education & A Bright Future',
    join_community: 'Join Our Community',
    learn_more: 'Learn More',
    our_mission: 'Our Mission',
    mission_text: 'To empower and mentor young women and girls in South Sudan to rise beyond societal limitations through education, storytelling, and mentorship helping them realize their worth and build independent, confident lives.',
    our_vision: 'Our Vision',
    vision_text: 'A South Sudan where every girl grows with courage, education, and purpose , free to dream, lead, and transform her community.',
    core_values: 'Our Core Values',
    respect: 'Respect',
    mentorship: 'Mentorship',
    diversity: 'Diversity',
    equality: 'Equality',
    inclusion: 'Inclusion',
    empowerment: 'Empowerment',
    collaboration: 'Collaboration',
    lifelong_learning: 'Lifelong Learning',
    goal_2030: 'Our 2030 Goal: Reach 10,000 Girls',
    goal_text: 'By 2030, we aim to connect 10,000 girls with resources for undergraduate opportunities, conferences, and internships.',
    '2030': '2030',
    '10,000': '10,000',
    fight_against: 'We Fight Against:',
    gender_inequality: 'Gender Inequality',
    gender_violence: 'Gender-Based Violence',
    early_marriage: 'Early Marriage',
    lack_opportunities: 'Lack of Opportunities',
    help_reach_goal: 'Help Us Reach Our Goal By:',
    joining_platform: 'Joining our platform to learn and connect',
    becoming_mentor: 'Becoming a mentor to guide young women',
    spreading_word: 'Spreading the word to reach more girls',
    supporting_mission: 'Supporting our mission and programs',
    
    // Home page translations
    'HerRaise Hub': 'HerRaise Hub',
    'Welcome to HerRaise Hub': 'Welcome to HerRaise Hub',
    'Watch our founder share the vision behind HerRaise Hub': 'Watch our founder share the vision behind HerRaise Hub',
    'HerRaise Mentorship Program': 'HerRaise Mentorship Program',
    'Become a Mentee to Advance Your Future': 'Become a Mentee to Advance Your Future',
    'Become a Mentor to Bridge the Gap and Make an Impact': 'Become a Mentor to Bridge the Gap and Make an Impact',
    'Featured Mentors': 'Featured Mentors',
    'Find Mentorship': 'Find Mentorship',
    'Get Started': 'Get Started',
    'Access Resources': 'Access Resources',
    'Browse Resources': 'Browse Resources',
    'Discover Opportunities': 'Discover Opportunities',
    'View Opportunities': 'View Opportunities',
    'Why Join HerRaise?': 'Why Join HerRaise?',
    'Build your network': 'Build your network',
    'Meet other ambitious young women and grow together through mentorship and friendship.': 'Meet other ambitious young women and grow together through mentorship and friendship.',
    'Develop your skills': 'Develop your skills',
    'Access training and workshops to build confidence, leadership, and tech skills.': 'Access training and workshops to build confidence, leadership, and tech skills.',
    'Unlock opportunities': 'Unlock opportunities',
    'Find the tools and connections that turn your dreams into action.': 'Find the tools and connections that turn your dreams into action.',
    'Join our community': 'Join our community',
    'Be part of a safe, supportive, and inspiring space made by women, for women.': 'Be part of a safe, supportive, and inspiring space made by women, for women.',
    'Join Our Community Today': 'Join Our Community Today',
    'How It Works': 'How It Works',
    'Sign Up': 'Sign Up',
    'Create your free HerRaise account in minutes.': 'Create your free HerRaise account in minutes.',
    'Build Your Profile': 'Build Your Profile',
    'Tell us about your goals and interests.': 'Tell us about your goals and interests.',
    'Connect With Mentors': 'Connect With Mentors',
    'Join mentorship programs and forums.': 'Join mentorship programs and forums.',
    'Achieve Your Goals': 'Achieve Your Goals',
    'Turn your learning into real-world action.': 'Turn your learning into real-world action.',
    'Start Your Journey Today': 'Start Your Journey Today',
    'Create Free Account': 'Create Free Account',
    'Sign In': 'Sign In',
    'Already have an account?': 'Already have an account?',
    'Login here': 'Login here',
    
    // Additional Home page content
    'Empowering the Next Generation of Women Leaders': 'Empowering the Next Generation of Women Leaders',
    'HerRaise Hub is a women led initiative dedicated to mentoring and empowering girls through education, confidence-building, and storytelling. We believe that every girl deserves the chance to rise above societal pressures, to dream boldly, and to take accountability for shaping her own future.': 'HerRaise Hub is a women led initiative dedicated to mentoring and empowering girls through education, confidence-building, and storytelling. We believe that every girl deserves the chance to rise above societal pressures, to dream boldly, and to take accountability for shaping her own future.',
    'Join the Movement': 'Join the Movement',
    'At HerRaise Hub, we believe that mentorship opens doors to growth and confidence. Whether you\'re exploring your education path, developing leadership and life skills, or preparing for career opportunities, this program connects you with inspiring women mentors who guide and empower you to reach higher.': 'At HerRaise Hub, we believe that mentorship opens doors to growth and confidence. Whether you\'re exploring your education path, developing leadership and life skills, or preparing for career opportunities, this program connects you with inspiring women mentors who guide and empower you to reach higher.',
    'Access scholarships': 'Access scholarships',
    'Find and apply for educational funding opportunities': 'Find and apply for educational funding opportunities',
    'Discover internships': 'Discover internships',
    'Connect with career-building experiences': 'Connect with career-building experiences',
    'Get guidance through forum discussions': 'Get guidance through forum discussions',
    'Connect with mentors in community forums': 'Connect with mentors in community forums',
    'Build confidence': 'Build confidence',
    'Develop skills and self-assurance for success': 'Develop skills and self-assurance for success',
    'Achieve your dreams': 'Achieve your dreams',
    'Turn aspirations into reality with expert help': 'Turn aspirations into reality with expert help',
    'Join HerRaise today and start your journey toward purpose, confidence, and success.': 'Join HerRaise today and start your journey toward purpose, confidence, and success.',
    'Apply for Mentorship': 'Apply for Mentorship',
    'Guide and support': 'Guide and support',
    'Stand with young girls amid the challenges they face': 'Stand with young girls amid the challenges they face',
    'Inspire through forum discussions': 'Inspire through forum discussions',
    'Share meaningful conversations and experiences': 'Share meaningful conversations and experiences',
    'Navigate opportunities': 'Navigate opportunities',
    'Help them find scholarships, internships, and programs': 'Help them find scholarships, internships, and programs',
    'Lead by example': 'Lead by example',
    'Share your knowledge and life experiences': 'Share your knowledge and life experiences',
    'Grow together': 'Grow together',
    'Mentors can also be mentees in our community': 'Mentors can also be mentees in our community',
    'Empower the next generation': 'Empower the next generation',
    'Help them reach their full potential': 'Help them reach their full potential',
    'Together, we can empower young women to rise with confidence and purpose.': 'Together, we can empower young women to rise with confidence and purpose.',
    'Become a Mentor': 'Become a Mentor',
    'Meet the inspiring women leaders guiding and empowering young girls across South Sudan and Africa': 'Meet the inspiring women leaders guiding and empowering young girls across South Sudan and Africa',
    'Join Our Mentor Community': 'Join Our Mentor Community',
    'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.': 'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.',
    'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.': 'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.',
    'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.': 'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.',
    'Because when you rise, your community rises with you.': 'Because when you rise, your community rises with you.',
    'Join thousands of young women taking charge of their future with courage, education, and purpose.': 'Join thousands of young women taking charge of their future with courage, education, and purpose.',
    
    // Mentor names and professions
    'Dr. Sarah Johnson': 'Dr. Sarah Johnson',
    'Education Director & Women Rights Advocate': 'Education Director & Women Rights Advocate',
    'Grace Akello': 'Grace Akello',
    'Tech Entrepreneur & Startup Founder': 'Tech Entrepreneur & Startup Founder',
    'Mary Nyandeng': 'Mary Nyandeng',
    'Healthcare Professional & Community Leader': 'Healthcare Professional & Community Leader',
    'Rebecca Garang': 'Rebecca Garang',
    'Legal Advisor & Human Rights Lawyer': 'Legal Advisor & Human Rights Lawyer',
    'Amina Hassan': 'Amina Hassan',
    'Financial Advisor & Business Consultant': 'Financial Advisor & Business Consultant',
    
    // Step numbers
    'step_1': '1️⃣',
    'step_2': '2️⃣',
    'step_3': '3️⃣',
    'step_4': '4️⃣',
    
    // Additional translations
    '10K': '10K',
    'BY 2030': 'BY 2030',
    'Join Our Mission': 'Join Our Mission',
    
    // Forum page translations
    'Community Forum': 'Community Forum',
    'Connect with peers, ask questions, and join discussions': 'Connect with peers, ask questions, and join discussions',
    'Ask Questions': 'Ask Questions',
    'Join Discussions': 'Join Discussions',
    'Get Support': 'Get Support',
    'Share Ideas': 'Share Ideas',
    'All Categories': 'All Categories',
    'New Post': 'New Post',
    'All': 'All',
    'Questions': 'Questions',
    'Discussions': 'Discussions',
    'sort_by': 'Sort by',
    'recent': 'Recent',
    'popular': 'Popular',
    'trending': 'Trending',
    'edited': 'edited',
    'view comments': 'View comments',
    'Comments': 'Comments',
    'comment': 'Add a comment...',
    'post comment': 'Post Comment',
    'comments': 'Comments',
    'no comments ': 'No comments yet. Be the first to comment!',
    'Start the conversation!': 'Start the conversation!',
    'Ask questions, share ideas, or start discussions with the community': 'Ask questions, share ideas, or start discussions with the community',
    'Start Your First Discussion': 'Start Your First Discussion',
    
    // CreatePostForm translations
    'Edit Post': 'Edit Post',
    'Start a Discussion': 'Start a Discussion',
    'Share your thoughts, ask questions, or start conversations with the community': 'Share your thoughts, ask questions, or start conversations with the community',
    'Category *': 'Category *',
    'Select a category...': 'Select a category...',
    'Subcategory *': 'Subcategory *',
    'Select a subcategory...': 'Select a subcategory...',
    'Suggested topics:': 'Suggested topics:',
    'Title *': 'Title *',
    'Enter a descriptive title...': 'Enter a descriptive title...',
    'Description *': 'Description *',
    'Share your thoughts, start a discussion, or ask for advice from the community...': 'Share your thoughts, start a discussion, or ask for advice from the community...',
    'characters': 'characters',
    'Tags (comma separated)': 'Tags (comma separated)',
    'e.g., technology, education, leadership': 'e.g., technology, education, leadership',
    'Add relevant tags to help others find your post': 'Add relevant tags to help others find your post',
    'Saving...': 'Saving...',
    'Update Post': 'Update Post',
    'Submit Post': 'Submit Post',
    'Cancel': 'Cancel',
    'Please login to continue': 'Please login to continue',
    
    // Remaining mentor section text
    'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.': 'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.',
    'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.': 'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.',
    'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.': 'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.'
  },
  
  // Swahili translations
  sw: {
    postNotFound: 'Chapisho halikupatikana.',
    commentNotFound: 'Maoni hayakupatikana.',
    liked: 'Imependwa',
    unliked: 'Imefutwa kupendwa',
    postCreated: 'Chapisho limeundwa.',
    commentCreated: 'Maoni yameongezwa.',
    notFound: 'Halikupatikana.',
    clickTracked: 'Kubonyeza imefuatiliwa.',
    bookmarked: 'Imewekwa alama.',
    unbookmarked: 'Alama imeondolewa.',
    types: 'Aina',
    
    // Add Swahili translations
    home: 'Nyumbani',
    about: 'Kuhusu',
    forum: 'Jukwaa',
    opportunities: 'Fursa',
    resources: 'Rasilimali',
    view_profile: 'Tazama Wasifu',
    dashboard: 'Dashibodi',
    settings: 'Mipangilio',
    help: 'Msaada',
    report_safety_concern: 'Ripoti Suala la Usalama',
    log_out: 'Toka',
    login: 'Ingia',
    register: 'Jisajili',
  },
  
  // Arabic translations
  ar: {
    postNotFound: 'المنشور غير موجود.',
    commentNotFound: 'التعليق غير موجود.',
    liked: 'أعجب',
    unliked: 'إلغاء الإعجاب',
    postCreated: 'تم إنشاء المنشور بنجاح.',
    commentCreated: 'تم نشر التعليق بنجاح.',
    notFound: 'غير موجود.',
    clickTracked: 'تم تتبع النقر.',
    bookmarked: 'تم الحفظ.',
    unbookmarked: 'تم إزالة الحفظ.',
    types: 'الأنواع',
    
    // Header translations
    home: 'الرئيسية',
    about: 'حول',
    forum: 'المنتدى',
    opportunities: 'الفرص',
    resources: 'الموارد',
    view_profile: 'عرض الملف الشخصي',
    dashboard: 'لوحة التحكم',
    settings: 'الإعدادات',
    help: 'المساعدة',
    report_safety_concern: 'الإبلاغ عن مخاوف الأمان',
    log_out: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    sharezone: 'منطقة المشاركة',
    
    // About page translations
    hero_title: 'كل فتاة تستحق التعليم ومستقبل مشرق',
    join_community: 'انضم إلى مجتمعنا',
    learn_more: 'تعلم المزيد',
    our_mission: 'مهمتنا',
    mission_text: 'تمكين وإرشاد الشابات والفتيات في جنوب السودان للارتقاء فوق القيود المجتمعية من خلال التعليم ورواية القصص والإرشاد لمساعدتهن على إدراك قيمتهن وبناء حياة مستقلة وواثقة.',
    our_vision: 'رؤيتنا',
    vision_text: 'جنوب السودان حيث تنمو كل فتاة بشجاعة وتعليم وهدف، حرة في أن تحلم وتقود وتحول مجتمعها.',
    core_values: 'قيمنا الأساسية',
    respect: 'الاحترام',
    mentorship: 'الإرشاد',
    diversity: 'التنوع',
    equality: 'المساواة',
    inclusion: 'الشمول',
    empowerment: 'التمكين',
    collaboration: 'التعاون',
    lifelong_learning: 'التعلم مدى الحياة',
    goal_2030: 'هدفنا ١٠٣٠: الوصول إلى ١٠،٠٠٠ فتاة',
    goal_text: 'بحلول عام ١٠٣٠، نهدف إلى ربط ١٠،٠٠٠ فتاة بالموارد لفرص البكالوريوس والمؤتمرات والتدريب.',
    '2030': '١٠٣٠',
    '10,000': '١٠،٠٠٠',
    fight_against: 'نحارب ضد:',
    gender_inequality: 'عدم المساواة بين الجنسين',
    gender_violence: 'العنف القائم على النوع',
    early_marriage: 'الزواج المبكر',
    lack_opportunities: 'نقص الفرص',
    help_reach_goal: 'ساعدنا في الوصول إلى هدفنا من خلال:',
    joining_platform: 'الانضمام إلى منصتنا للتعلم والتواصل',
    becoming_mentor: 'أن تصبح مرشداً لتوجيه الشابات',
    spreading_word: 'نشر الكلمة للوصول إلى المزيد من الفتيات',
    supporting_mission: 'دعم مهمتنا وبرامجنا',
    
    // Home page Arabic translations
    'HerRaise Hub': 'هير رايز هاب',
    'Welcome to HerRaise Hub': 'مرحباً بكم في هير رايز هاب',
    'Watch our founder share the vision behind HerRaise Hub': 'شاهد مؤسستنا تشارك الرؤية وراء هير رايز هاب',
    'HerRaise Mentorship Program': 'برنامج الإرشاد في هير رايز',
    'Become a Mentee to Advance Your Future': 'كن متدربة لتطوير مستقبلك',
    'Become a Mentor to Bridge the Gap and Make an Impact': 'كن مرشدة لسد الفجوة وإحداث تأثير',
    'Featured Mentors': 'المرشدات المميزات',
    'Find Mentorship': 'العثور على الإرشاد',
    'Get Started': 'ابدأ الآن',
    'Access Resources': 'الوصول للموارد',
    'Browse Resources': 'تصفح الموارد',
    'Discover Opportunities': 'اكتشف الفرص',
    'View Opportunities': 'عرض الفرص',
    'Why Join HerRaise?': 'لماذا تنضم إلى هير رايز؟',
    'Build your network': 'بناء شبكتك',
    'Meet other ambitious young women and grow together through mentorship and friendship.': 'التقي بشابات طموحات أخريات وانمي معاً من خلال الإرشاد والصداقة.',
    'Develop your skills': 'طور مهاراتك',
    'Access training and workshops to build confidence, leadership, and tech skills.': 'احصل على التدريب وورش العمل لبناء الثقة والقيادة والمهارات التقنية.',
    'Unlock opportunities': 'افتح الفرص',
    'Find the tools and connections that turn your dreams into action.': 'اعثر على الأدوات والاتصالات التي تحول أحلامك إلى عمل.',
    'Join our community': 'انضم إلى مجتمعنا',
    'Be part of a safe, supportive, and inspiring space made by women, for women.': 'كن جزءاً من مساحة آمنة وداعمة وملهمة صنعتها النساء للنساء.',
    'Join Our Community Today': 'انضم إلى مجتمعنا اليوم',
    'How It Works': 'كيف يعمل',
    'Sign Up': 'التسجيل',
    'Create your free HerRaise account in minutes.': 'أنشئ حسابك المجاني في هير رايز خلال دقائق.',
    'Build Your Profile': 'بناء ملفك الشخصي',
    'Tell us about your goals and interests.': 'أخبرنا عن أهدافك واهتماماتك.',
    'Connect With Mentors': 'التواصل مع المرشدين',
    'Join mentorship programs and forums.': 'انضم إلى برامج الإرشاد والمنتديات.',
    'Achieve Your Goals': 'حقق أهدافك',
    'Turn your learning into real-world action.': 'حول تعلمك إلى عمل في العالم الحقيقي.',
    'Start Your Journey Today': 'ابدأ رحلتك اليوم',
    'Create Free Account': 'إنشاء حساب مجاني',
    'Sign In': 'تسجيل الدخول',
    'Already have an account?': 'هل لديك حساب بالفعل؟',
    'Login here': 'سجل الدخول هنا',
    
    // Additional Home page Arabic content
    'Empowering the Next Generation of Women Leaders': 'تمكين الجيل القادم من القائدات',
    'HerRaise Hub is a women led initiative dedicated to mentoring and empowering girls through education, confidence-building, and storytelling. We believe that every girl deserves the chance to rise above societal pressures, to dream boldly, and to take accountability for shaping her own future.': 'هير رايز هاب هي مبادرة تقودها النساء مكرسة لإرشاد وتمكين الفتيات من خلال التعليم وبناء الثقة ورواية القصص. نحن نؤمن أن كل فتاة تستحق الفرصة للارتقاء فوق الضغوط المجتمعية، وأن تحلم بجرأة، وأن تتحمل المسؤولية في تشكيل مستقبلها.',
    'Join the Movement': 'انضم إلى الحركة',
    'At HerRaise Hub, we believe that mentorship opens doors to growth and confidence. Whether you\'re exploring your education path, developing leadership and life skills, or preparing for career opportunities, this program connects you with inspiring women mentors who guide and empower you to reach higher.': 'في هير رايز هاب، نؤمن أن الإرشاد يفتح أبواب النمو والثقة. سواء كنت تستكشف مسارك التعليمي، أو تطور مهارات القيادة والحياة، أو تستعد لفرص مهنية، يربطك هذا البرنامج بمرشدات ملهمات يوجهنك ويمكنك من الوصول إلى أعلى.',
    'Access scholarships': 'الوصول للمنح الدراسية',
    'Find and apply for educational funding opportunities': 'العثور على فرص التمويل التعليمي والتقدم لها',
    'Discover internships': 'اكتشاف التدريبات',
    'Connect with career-building experiences': 'التواصل مع تجارب بناء المهنة',
    'Get guidance through forum discussions': 'الحصول على التوجيه من خلال مناقشات المنتدى',
    'Connect with mentors in community forums': 'التواصل مع المرشدين في منتديات المجتمع',
    'Build confidence': 'بناء الثقة',
    'Develop skills and self-assurance for success': 'تطوير المهارات والثقة بالنفس للنجاح',
    'Achieve your dreams': 'حقق أحلامك',
    'Turn aspirations into reality with expert help': 'حول التطلعات إلى واقع بمساعدة الخبراء',
    'Join HerRaise today and start your journey toward purpose, confidence, and success.': 'انضم إلى هير رايز اليوم وابدأ رحلتك نحو الهدف والثقة والنجاح.',
    'Apply for Mentorship': 'التقدم للإرشاد',
    'Guide and support': 'التوجيه والدعم',
    'Stand with young girls amid the challenges they face': 'الوقوف مع الفتيات الصغيرات وسط التحديات التي يواجهنها',
    'Inspire through forum discussions': 'الإلهام من خلال مناقشات المنتدى',
    'Share meaningful conversations and experiences': 'مشاركة المحادثات والتجارب المعنوية',
    'Navigate opportunities': 'التنقل في الفرص',
    'Help them find scholarships, internships, and programs': 'مساعدتهن في العثور على المنح والتدريبات والبرامج',
    'Lead by example': 'القيادة بالمثال',
    'Share your knowledge and life experiences': 'مشاركة معرفتك وتجارب حياتك',
    'Grow together': 'النمو معاً',
    'Mentors can also be mentees in our community': 'يمكن للمرشدين أيضاً أن يكونوا متدربين في مجتمعنا',
    'Empower the next generation': 'تمكين الجيل القادم',
    'Help them reach their full potential': 'مساعدتهن على الوصول إلى إمكاناتهن الكاملة',
    'Together, we can empower young women to rise with confidence and purpose.': 'معاً، يمكننا تمكين الشابات للارتقاء بثقة وهدف.',
    'Become a Mentor': 'كن مرشداً',
    'Meet the inspiring women leaders guiding and empowering young girls across South Sudan and Africa': 'تعرف على القائدات الملهمات اللواتي يوجهن ويمكن الفتيات الصغيرات عبر جنوب السودان وأفريقيا',
    'Join Our Mentor Community': 'انضم إلى مجتمع المرشدين لدينا',
    'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.': 'تواصل مع مرشدين ملهمين يوجهونك في التعليم والمهنة والنمو الشخصي. لست تسير في هذه الرحلة وحدك.',
    'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.': 'استكشف مواد التعلم حول الثقة والقيادة وبناء المهنة والتطوير الشخصي المصممة خصيصاً للشابات.',
    'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.': 'تعلم عن المنح الدراسية والتدريبات والفرص العالمية التي يمكن أن تساعدك في تحقيق أحلامك.',
    'Because when you rise, your community rises with you.': 'لأنه عندما ترتقي، يرتقي مجتمعك معك.',
    'Join thousands of young women taking charge of their future with courage, education, and purpose.': 'انضم إلى آلاف الشابات اللواتي يتحكمن في مستقبلهن بشجاعة وتعليم وهدف.',
    
    // Mentor professions in Arabic (names stay in English)
    'Education Director & Women Rights Advocate': 'مديرة التعليم ومدافعة عن حقوق المرأة',
    'Tech Entrepreneur & Startup Founder': 'رائدة أعمال تقنية ومؤسسة شركة ناشئة',
    'Healthcare Professional & Community Leader': 'أخصائية رعاية صحية وقائدة مجتمعية',
    'Legal Advisor & Human Rights Lawyer': 'مستشارة قانونية ومحامية حقوق إنسان',
    'Financial Advisor & Business Consultant': 'مستشارة مالية واستشارية أعمال',
    
    // Arabic step numbers
    'step_1': '١️⃣',
    'step_2': '٢️⃣',
    'step_3': '٣️⃣',
    'step_4': '٤️⃣',
    
    // Remaining mentor section Arabic text
    'Connect with inspiring mentors who guide you in education, career, and personal growth. You don\'t walk this journey alone.': 'تواصل مع مرشدين ملهمين يوجهونك في التعليم والمهنة والنمو الشخصي. لست تسير في هذه الرحلة وحدك.',
    'Explore learning materials on confidence, leadership, career building, and personal development designed just for young women.': 'استكشف مواد التعلم حول الثقة والقيادة وبناء المهنة والتطوير الشخصي المصممة خصيصاً للشابات.',
    'Learn about scholarships, internships, and global opportunities that can help you take charge of your dreams.': 'تعلم عن المنح الدراسية والتدريبات والفرص العالمية التي يمكن أن تساعدك في تحقيق أحلامك.',
    
    // About page additional translations
    'Success Stories from Our Community': 'قصص نجاح من مجتمعنا',
    'Hear from young women whose lives have been transformed by HerRaise Hub': 'استمع إلى الشابات اللواتي تغيرت حياتهن بفضل هير رايز هاب',
    'Secondary School Student': 'طالبة مدرسة ثانوية',
    'University Student': 'طالبة جامعية',
    'High School Graduate': 'خريجة مدرسة ثانوية',
    'Our Community Guidelines': 'إرشادات مجتمعنا',
    'Creating a safe, supportive, and empowering space for all members': 'إنشاء مساحة آمنة وداعمة ومُمكِّنة لجميع الأعضاء',
    'Be Respectful': 'كن محترماً',
    'Treat everyone with kindness and dignity': 'تعامل مع الجميع بلطف وكرامة',
    'Embrace Inclusivity': 'احتضن الشمولية',
    'Celebrate diversity and welcome all voices': 'احتفل بالتنوع ورحب بجميع الأصوات',
    'Communicate Positively': 'تواصل بإيجابية',
    'Use encouraging and constructive language': 'استخدم لغة مشجعة وبناءة',
    'Stay Safe': 'ابق آمناً',
    'Protect your privacy and report concerns': 'احم خصوصيتك وأبلغ عن المخاوف',
    'Support Each Other': 'ادعموا بعضكم البعض',
    'Lift others up and share knowledge': 'ارفعوا الآخرين وشاركوا المعرفة',
    'Be Authentic': 'كن أصيلاً',
    'Share genuine experiences and advice': 'شارك التجارب والنصائح الحقيقية',
    'Ready to Make a Difference?': 'مستعد لإحداث فرق؟',
    'Join thousands of young women and mentors creating positive change together': 'انضم إلى آلاف الشابات والمرشدين الذين يخلقون تغييراً إيجابياً معاً',
    'Create Account': 'إنشاء حساب',
    'Explore Opportunities': 'استكشف الفرص',
    'BY 2030': 'بحلول 2030',
    '10K': '10آلاف',
    'Join Our Mission': 'انضم إلى مهمتنا',
    
    // Forum page Arabic translations
    'Community Forum': 'منتدى المجتمع',
    'Connect with peers, ask questions, and join discussions': 'تواصل مع الزملاء، اطرح الأسئلة، وانضم إلى النقاشات',
    'Ask Questions': 'اطرح الأسئلة',
    'Join Discussions': 'انضم إلى النقاشات',
    'Get Support': 'احصل على الدعم',
    'Share Ideas': 'شارك الأفكار',
    'All Categories': 'جميع الفئات',
    'New Post': 'منشور جديد',
    'All': 'الكل',
    'Questions': 'الأسئلة',
    'Discussions': 'النقاشات',
    'sort_by': 'ترتيب حسب',
    'recent': 'الأحدث',
    'popular': 'الأكثر شعبية',
    'trending': 'الرائج',
    'edited': 'مُعدّل',
    'view comments': 'عرض التعليقات',
    'Comments': 'التعليقات',
    'comment': 'أضف تعليقاً...',
    'post comment': 'نشر التعليق',
    'comments': 'التعليقات',
    'no comments ': 'لا توجد تعليقات بعد. كن أول من يعلق!',
    'Start the conversation!': 'ابدأ المحادثة!',
    'Ask questions, share ideas, or start discussions with the community': 'اطرح الأسئلة، شارك الأفكار، أو ابدأ نقاشات مع المجتمع',
    'Start Your First Discussion': 'ابدأ نقاشتك الأولى',
    
    // CreatePostForm Arabic translations
    'Edit Post': 'تعديل المنشور',
    'Start a Discussion': 'ابدأ نقاشاً',
    'Share your thoughts, ask questions, or start conversations with the community': 'شارك أفكارك، اطرح الأسئلة، أو ابدأ محادثات مع المجتمع',
    'Category *': 'الفئة *',
    'Select a category...': 'اختر فئة...',
    'Subcategory *': 'الفئة الفرعية *',
    'Select a subcategory...': 'اختر فئة فرعية...',
    'Suggested topics:': 'مواضيع مقترحة:',
    'Title *': 'العنوان *',
    'Enter a descriptive title...': 'أدخل عنواناً وصفياً...',
    'Description *': 'الوصف *',
    'Share your thoughts, start a discussion, or ask for advice from the community...': 'شارك أفكارك، ابدأ نقاشاً، أو اطلب النصيحة من المجتمع...',
    'characters': 'حرف',
    'Tags (comma separated)': 'العلامات (مفصولة بفواصل)',
    'e.g., technology, education, leadership': 'مثل: التكنولوجيا، التعليم، القيادة',
    'Add relevant tags to help others find your post': 'أضف علامات ذات صلة لمساعدة الآخرين في العثور على منشورك',
    'Saving...': 'حفظ...',
    'Update Post': 'تحديث المنشور',
    'Submit Post': 'نشر المنشور',
    'Cancel': 'إلغاء',
    'Please login to continue': 'يرجى تسجيل الدخول للمتابعة',
    
    // Testimonial stories
    'HerRaise Hub connected me with an amazing mentor who guided me through my college application process. I never thought I could apply to universities abroad, but now I have acceptance letters from three universities! This platform changed my life and showed me that my dreams are valid and achievable.': 'ربطتني هير رايز هاب بمرشدة رائعة وجهتني خلال عملية التقديم للجامعة. لم أعتقد أبداً أنني يمكنني التقديم لجامعات في الخارج، لكن الآن لدي خطابات قبول من ثلاث جامعات! غيرت هذه المنصة حياتي وأظهرت لي أن أحلامي صحيحة وقابلة للتحقيق.',
    'Through HerRaise Hub, I found scholarship opportunities I never knew existed. The community here is so supportive and encouraging. I secured a full scholarship for my undergraduate studies and now I mentor younger girls on the platform. It\'s incredible to pay forward the help I received.': 'من خلال هير رايز هاب، وجدت فرص منح دراسية لم أعرف بوجودها. المجتمع هنا داعم ومشجع جداً. حصلت على منحة دراسية كاملة لدراساتي الجامعية والآن أرشد فتيات أصغر على المنصة. من الرائع رد الجميل للمساعدة التي تلقيتها.',
    'Before joining HerRaise Hub, I felt alone in my journey. Now I have a network of peers and mentors who understand my challenges. The resources section helped me prepare for standardized tests, and I just got accepted into my dream internship program. I\'m so grateful for this platform!': 'قبل الانضمام إلى هير رايز هاب، شعرت بالوحدة في رحلتي. الآن لدي شبكة من الزميلات والمرشدين الذين يفهمون تحدياتي. قسم الموارد ساعدني في الاستعداد للاختبارات المعيارية، وقد تم قبولي في برنامج التدريب الذي أحلم به. أنا ممتنة جداً لهذه المنصة!'
  }
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  
  // Get current language from context
  const { language } = context
  
  // Create t function that uses current language
  const t = (key) => {
    const currentLang = language || 'en'
    return translations[currentLang]?.[key] || key
  }
  
  // FIX: Return context WITH the t function
  return { ...context, t }
}